config/routes.rb
Rails.application.routes.draw do
  resources :shops
  resources :town_details
  resources :towns
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  authenticate :user do
    root 'dashboard#home'
  end

  authenticated :user do
    get '/', to: 'dashboard#home', as: 'auth_home'
  end

end

app/models/shop.rb
class Shop < ApplicationRecord
  belongs_to :town
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops or /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully created." }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to shop_url(@shop), notice: "Shop was successfully updated." }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy

    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.require(:shop).permit(:name, :town_id, :kind)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.erb
<%= form_with(model: shop) do |form| %>
  <% if shop.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
        <% shop.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :town_id, style: "display: block" %>
    <%= form.text_field :town_id %>
  </div>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%= form.number_field :kind %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p>
    <strong>Name:</strong>
    <%= shop.name %>
  </p>

  <p>
    <strong>Town:</strong>
    <%= shop.town_id %>
  </p>

  <p>
    <strong>Kind:</strong>
    <%= shop.kind %>
  </p>

</div>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Show this shop", @shop %> |
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shops</h1>

<div id="shops">
  <% @shops.each do |shop| %>
    <%= render shop %>
    <p>
      <%= link_to "Show this shop", shop %>
    </p>
  <% end %>
</div>

<%= link_to "New shop", new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render "form", shop: @shop %>

<br>

<div>
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shop %>

<div>
  <%= link_to "Edit this shop", edit_shop_path(@shop) %> |
  <%= link_to "Back to shops", shops_path %>

  <%= button_to "Destroy this shop", @shop, method: :delete %>
</div>