config/routes.rb
Rails.application.routes.draw do
  resources :shops
  resources :town_details
  resources :towns
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  authenticate :user do
    root 'dashboard#home'
  end

  authenticated :user do
    get '/', to: 'dashboard#home', as: 'auth_home'
  end

end

app/models/town_detail.rb
class TownDetail < ApplicationRecord
  belongs_to :town

  enum size: {
    thorp: 1,
    hamlet: 2, 
    village: 3,
    small_town: 4,
    large_town: 5,
    small_city: 6,
    large_city: 7,
    metropolis: 8
  }
end

app/controllers/town_details_controller.rb
class TownDetailsController < ApplicationController
  before_action :set_town_detail, only: %i[ show edit update destroy ]

  # GET /town_details or /town_details.json
  def index
    @town_details = TownDetail.all
  end

  # GET /town_details/1 or /town_details/1.json
  def show
  end

  # GET /town_details/new
  def new
    @town_detail = TownDetail.new
  end

  # GET /town_details/1/edit
  def edit
  end

  # POST /town_details or /town_details.json
  def create
    @town_detail = TownDetail.new(town_detail_params)

    respond_to do |format|
      if @town_detail.save
        format.html { redirect_to town_detail_url(@town_detail), notice: "Town detail was successfully created." }
        format.json { render :show, status: :created, location: @town_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @town_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /town_details/1 or /town_details/1.json
  def update
    respond_to do |format|
      if @town_detail.update(town_detail_params)
        format.html { redirect_to town_detail_url(@town_detail), notice: "Town detail was successfully updated." }
        format.json { render :show, status: :ok, location: @town_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @town_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /town_details/1 or /town_details/1.json
  def destroy
    @town_detail.destroy

    respond_to do |format|
      format.html { redirect_to town_details_url, notice: "Town detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town_detail
      @town_detail = TownDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def town_detail_params
      params.require(:town_detail).permit(:town_id, :size, :population)
    end
end

app/helpers/town_details_helper.rb
module TownDetailsHelper
end

app/views/town_details/_form.html.erb
<%= form_with(model: town_detail) do |form| %>
  <% if town_detail.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(town_detail.errors.count, "error") %> prohibited this town_detail from being saved:</h2>

      <ul>
        <% town_detail.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :town_id, style: "display: block" %>
    <%= form.text_field :town_id %>
  </div>

  <div>
    <%= form.label :size, style: "display: block" %>
    <%= form.number_field :size %>
  </div>

  <div>
    <%= form.label :population, style: "display: block" %>
    <%= form.number_field :population %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/town_details/_town_detail.html.erb
<div id="<%= dom_id town_detail %>">
  <p>
    <strong>Town:</strong>
    <%= town_detail.town_id %>
  </p>

  <p>
    <strong>Size:</strong>
    <%= town_detail.size %>
  </p>

  <p>
    <strong>Population:</strong>
    <%= town_detail.population %>
  </p>

</div>

app/views/town_details/edit.html.erb
<h1>Editing town detail</h1>

<%= render "form", town_detail: @town_detail %>

<br>

<div>
  <%= link_to "Show this town detail", @town_detail %> |
  <%= link_to "Back to town details", town_details_path %>
</div>

app/views/town_details/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Town details</h1>

<div id="town_details">
  <% @town_details.each do |town_detail| %>
    <%= render town_detail %>
    <p>
      <%= link_to "Show this town detail", town_detail %>
    </p>
  <% end %>
</div>

<%= link_to "New town detail", new_town_detail_path %>

app/views/town_details/new.html.erb
<h1>New town detail</h1>

<%= render "form", town_detail: @town_detail %>

<br>

<div>
  <%= link_to "Back to town details", town_details_path %>
</div>

app/views/town_details/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @town_detail %>

<div>
  <%= link_to "Edit this town detail", edit_town_detail_path(@town_detail) %> |
  <%= link_to "Back to town details", town_details_path %>

  <%= button_to "Destroy this town detail", @town_detail, method: :delete %>
</div>