config/routes.rb
Rails.application.routes.draw do
  resources :shops
  resources :town_details
  resources :towns
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"


  authenticate :user do
    root 'dashboard#home'
  end

  authenticated :user do
    get '/', to: 'dashboard#home', as: 'auth_home'
  end

end

app/models/town.rb
class Town < ApplicationRecord
end

app/controllers/towns_controller.rb
class TownsController < ApplicationController
  before_action :set_town, only: %i[ show edit update destroy ]

  # GET /towns or /towns.json
  def index
    @towns = Town.all
  end

  # GET /towns/1 or /towns/1.json
  def show
  end

  # GET /towns/new
  def new
    @town = Town.new
  end

  # GET /towns/1/edit
  def edit
  end

  # POST /towns or /towns.json
  def create
    @town = Town.new(town_params)

    respond_to do |format|
      if @town.save
        format.html { redirect_to town_url(@town), notice: "Town was successfully created." }
        format.json { render :show, status: :created, location: @town }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /towns/1 or /towns/1.json
  def update
    respond_to do |format|
      if @town.update(town_params)
        format.html { redirect_to town_url(@town), notice: "Town was successfully updated." }
        format.json { render :show, status: :ok, location: @town }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @town.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /towns/1 or /towns/1.json
  def destroy
    @town.destroy

    respond_to do |format|
      format.html { redirect_to towns_url, notice: "Town was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_town
      @town = Town.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def town_params
      params.require(:town).permit(:name, :description)
    end
end

app/helpers/towns_helper.rb
module TownsHelper
end

app/views/towns/_form.html.erb
<%= form_with(model: town) do |form| %>
  <% if town.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(town.errors.count, "error") %> prohibited this town from being saved:</h2>

      <ul>
        <% town.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/towns/_town.html.erb
<div id="<%= dom_id town %>">
  <p>
    <strong>Name:</strong>
    <%= town.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= town.description %>
  </p>

</div>

app/views/towns/edit.html.erb
<h1>Editing town</h1>

<%= render "form", town: @town %>

<br>

<div>
  <%= link_to "Show this town", @town %> |
  <%= link_to "Back to towns", towns_path %>
</div>

app/views/towns/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Towns</h1>

<div id="towns">
  <% @towns.each do |town| %>
    <%= render town %>
    <p>
      <%= link_to "Show this town", town %>
    </p>
  <% end %>
</div>

<%= link_to "New town", new_town_path %>

app/views/towns/new.html.erb
<h1>New town</h1>

<%= render "form", town: @town %>

<br>

<div>
  <%= link_to "Back to towns", towns_path %>
</div>

app/views/towns/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @town %>

<div>
  <%= link_to "Edit this town", edit_town_path(@town) %> |
  <%= link_to "Back to towns", towns_path %>

  <%= button_to "Destroy this town", @town, method: :delete %>
</div>